### ISSUE TITLE
Quest2とVirtual Desktopの組み合わせでパーティクルがデカくなる

### ISSUE THREAD

**Issue by Kuwamai** [Kuwamai/HipParticle#2]
Phi16さんに教えていただいたところナウいやり方だとView座標系で計算するみたい。

https://github.com/phi16/VRC_storage/blob/master/phi_util/BasicParticle.shader#L57

**Comment by RamType0** [comment]
View座標系でのビルボードもPimaxで動かないです・・・
実際FuwaParticleもPimaxだとうまく動かない・・・

**Comment by Kuwamai** [comment]
え、Pimaxも特殊なんですか…! AndroidとWindows対応で済むかと思ってたのですが色々ややこしいのですね…。

**Comment by RamType0** [comment]
> え、Pimaxも特殊なんですか…! AndroidとWindows対応で済むかと思ってたのですが色々ややこしいのですね…。

https://qiita.com/RamType0/items/baf2b9d5ce0f9fc458be

この記事で詳しく書いてますが、今後VRHMDの広視野角化が進めば他のHMDでも同じ問題が発生すると思われます。

ようは、Pimaxだと両目それぞれの向きが違うから両目それぞれに正対するビルボード出そうとすると両目で違う向きになっちゃうよ、ということです

**Comment by Kuwamai** [comment]
ああ! カメラの向きの話は以前何かで聞いたことありました。確かにビルボードは原理的にダメですね…。

**Comment by RamType0** [comment]
> ああ! カメラの向きの話は以前何かで聞いたことありました。確かにビルボードは原理的にダメですね…。

今回のこれで、Pimaxも対応してます。
